using System;
using System.Data.Entity.Migrations;
using Microsoft.AspNet.Identity;
using Notus.Portal.Models;

namespace Notus.Portal.Migrations
{
    internal sealed class Configuration : DbMigrationsConfiguration<ApplicationDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
        }

        protected override void Seed(ApplicationDbContext context)
        {
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method 
            //  to avoid creating duplicate seed data. E.g.
            //
            //    context.People.AddOrUpdate(
            //      p => p.FullName,
            //      new Person { FullName = "Andrew Peters" },
            //      new Person { FullName = "Brice Lambson" },
            //      new Person { FullName = "Rowan Miller" }
            //    );
            //
            var countries = new[]
            {
                new Country {Name = "Brazil", Code = "BR"},
                new Country {Name = "British Indian Ocean Territory", Code = "IO"},
                new Country {Name = "Brunei", Code = "BN"},
                new Country {Name = "Bulgaria", Code = "BG"},
                new Country {Name = "Burkina Faso", Code = "BF"},
                new Country {Name = "Djibouti", Code = "DJ"},
                new Country {Name = "Dominica", Code = "DM"},
                new Country {Name = "Dominican Republic", Code = "DO"},
                new Country {Name = "Ecuador", Code = "EC"},
                new Country {Name = "Egypt", Code = "EG"},
                new Country {Name = "El Salvador", Code = "SV"},
                new Country {Name = "Equatorial Guinea", Code = "GQ"},
                new Country {Name = "Eritrea", Code = "ER"},
                new Country {Name = "Estonia", Code = "EE"},
                new Country {Name = "Ethiopia", Code = "ET"},
                new Country {Name = "Falkland Islands", Code = "FK"},
                new Country {Name = "Faroe Islands", Code = "FO"},
                new Country {Name = "Fiji Islands", Code = "FJ"},
                new Country {Name = "Finland", Code = "FI"},
                new Country {Name = "France", Code = "FR"},
                new Country {Name = "French Guiana", Code = "GF"},
                new Country {Name = "French Polynesia", Code = "PF"},
                new Country {Name = "French Southern and Antarctic Lands", Code = "TF"},
                new Country {Name = "Gabon", Code = "GA"},
                new Country {Name = "Gambia, The", Code = "GM"},
                new Country {Name = "Georgia", Code = "GE"},
                new Country {Name = "Germany", Code = "DE"},
                new Country {Name = "Ghana", Code = "GH"},
                new Country {Name = "Gibraltar", Code = "GI"},
                new Country {Name = "Greece", Code = "GR"},
                new Country {Name = "Greenland", Code = "GL"},
                new Country {Name = "Grenada", Code = "GD"},
                new Country {Name = "Guadeloupe", Code = "GP"},
                new Country {Name = "Guam", Code = "GU"},
                new Country {Name = "Guatemala", Code = "GT"},
                new Country {Name = "Guernsey", Code = "GG"},
                new Country {Name = "Guinea", Code = "GN"},
                new Country {Name = "Guinea-Bissau", Code = "GW"},
                new Country {Name = "Guyana", Code = "GY"},
                new Country {Name = "Haiti", Code = "HT"},
                new Country {Name = "Heard Island and McDonald Islands", Code = "HM"},
                new Country {Name = "Holy See (Vatican City)", Code = "VA"},
                new Country {Name = "Honduras", Code = "HN"},
                new Country {Name = "Hong Kong SAR", Code = "HK"},
                new Country {Name = "Hungary", Code = "HU"},
                new Country {Name = "Iceland", Code = "IS"},
                new Country {Name = "India", Code = "IN"},
                new Country {Name = "Indonesia", Code = "ID"},
                new Country {Name = "Iran", Code = "IR"},
                new Country {Name = "Iraq", Code = "IQ"},
                new Country {Name = "Ireland", Code = "IE"},
                new Country {Name = "Isle of Man", Code = "IM"},
                new Country {Name = "Israel", Code = "IL"},
                new Country {Name = "Italy", Code = "IT"},
                new Country {Name = "Jamaica", Code = "JM"},
                new Country {Name = "Jan Mayen", Code = "SJ"},
                new Country {Name = "Japan", Code = "JP"},
                new Country {Name = "Jersey", Code = "JE"},
                new Country {Name = "Jordan", Code = "JO"},
                new Country {Name = "Kazakhstan", Code = "KZ"},
                new Country {Name = "Kenya", Code = "KE"},
                new Country {Name = "Kiribati", Code = "KI"},
                new Country {Name = "Korea", Code = "KR"},
                new Country {Name = "Kosovo", Code = "XK"},
                new Country {Name = "Kuwait", Code = "KW"},
                new Country {Name = "Kyrgyzstan", Code = "KG"},
                new Country {Name = "Laos", Code = "LA"},
                new Country {Name = "Latvia", Code = "LV"},
                new Country {Name = "Lebanon", Code = "LB"},
                new Country {Name = "Lesotho", Code = "LS"},
                new Country {Name = "Liberia", Code = "LR"},
                new Country {Name = "Libya", Code = "LY"},
                new Country {Name = "Liechtenstein", Code = "LI"},
                new Country {Name = "Lithuania", Code = "LT"},
                new Country {Name = "Luxembourg", Code = "LU"},
                new Country {Name = "Macao SAR", Code = "MO"},
                new Country {Name = "Macedonia, Former Yugoslav Republic of", Code = "MK"},
                new Country {Name = "Madagascar", Code = "MG"},
                new Country {Name = "Malawi", Code = "MW"},
                new Country {Name = "Malaysia", Code = "MY"},
                new Country {Name = "Maldives", Code = "MV"},
                new Country {Name = "Mali", Code = "ML"},
                new Country {Name = "Malta", Code = "MT"},
                new Country {Name = "Marshall Islands", Code = "MH"},
                new Country {Name = "Martinique", Code = "MQ"},
                new Country {Name = "Mauritania", Code = "MR"},
                new Country {Name = "Mauritius", Code = "MU"},
                new Country {Name = "Mayotte", Code = "YT"},
                new Country {Name = "Mexico", Code = "MX"},
                new Country {Name = "Micronesia", Code = "FM"},
                new Country {Name = "Moldova", Code = "MD"},
                new Country {Name = "Monaco", Code = "MC"},
                new Country {Name = "Mongolia", Code = "MN"},
                new Country {Name = "Montenegro", Code = "ME"},
                new Country {Name = "Montserrat", Code = "MS"},
                new Country {Name = "Morocco", Code = "MA"},
                new Country {Name = "Mozambique", Code = "MZ"},
                new Country {Name = "Myanmar", Code = "MM"},
                new Country {Name = "Namibia", Code = "NA"},
                new Country {Name = "Nauru", Code = "NR"},
                new Country {Name = "Nepal", Code = "NP"},
                new Country {Name = "Netherlands", Code = "NL"},
                new Country {Name = "Netherlands Antilles (Former)", Code = "AN"},
                new Country {Name = "Caledonia", Code = "NC"},
                new Country {Name = "Zealand", Code = "NZ"},
                new Country {Name = "Nicaragua", Code = "NI"},
                new Country {Name = "Niger", Code = "NE"},
                new Country {Name = "Nigeria", Code = "NG"},
                new Country {Name = "Niue", Code = "NU"},
                new Country {Name = "Norfolk Island", Code = "NF"},
                new Country {Name = "North Korea", Code = "KP"},
                new Country {Name = "Northern Mariana Islands", Code = "MP"},
                new Country {Name = "Norway", Code = "NO"},
                new Country {Name = "Oman", Code = "OM"},
                new Country {Name = "Pakistan", Code = "PK"},
                new Country {Name = "Palau", Code = "PW"},
                new Country {Name = "Palestinian Authority", Code = "PS"},
                new Country {Name = "Panama", Code = "PA"},
                new Country {Name = "Papua New Guinea", Code = "PG"},
                new Country {Name = "Paraguay", Code = "PY"},
                new Country {Name = "Peru", Code = "PE"},
                new Country {Name = "Philippines", Code = "PH"},
                new Country {Name = "Pitcairn Islands", Code = "PN"},
                new Country {Name = "Poland", Code = "PL"},
                new Country {Name = "Portugal", Code = "PT"},
                new Country {Name = "Puerto Rico", Code = "PR"},
                new Country {Name = "Qatar", Code = "QA"},
                new Country {Name = "Republic of Côte d'Ivoire", Code = "CI"},
                new Country {Name = "Reunion", Code = "RE"},
                new Country {Name = "Romania", Code = "RO"},
                new Country {Name = "Russia", Code = "RU"},
                new Country {Name = "Rwanda", Code = "RW"},
                new Country {Name = "Saba", Code = "XS"},
                new Country {Name = "Saint Helena, Ascension and Tristan da Cunha", Code = "SH"},
                new Country {Name = "Samoa", Code = "WS"},
                new Country {Name = "San Marino", Code = "SM"},
                new Country {Name = "São Tomé and Príncipe", Code = "ST"},
                new Country {Name = "Saudi Arabia", Code = "SA"},
                new Country {Name = "Senegal", Code = "SN"},
                new Country {Name = "Serbia", Code = "RS"},
                new Country {Name = "Serbia, Montenegro", Code = "YU"},
                new Country {Name = "Seychelles", Code = "SC"},
                new Country {Name = "Sierra Leone", Code = "SL"},
                new Country {Name = "Singapore", Code = "SG"},
                new Country {Name = "Sint Eustatius", Code = "XE"},
                new Country {Name = "Sint Maarten", Code = "SX"},
                new Country {Name = "Slovakia", Code = "SK"},
                new Country {Name = "Slovenia", Code = "SI"},
                new Country {Name = "Solomon Islands", Code = "SB"},
                new Country {Name = "Somalia", Code = "SO"},
                new Country {Name = "South Africa", Code = "ZA"},
                new Country {Name = "South Georgia and the South Sandwich Islands", Code = "GS"},
                new Country {Name = "Spain", Code = "ES"},
                new Country {Name = "Sri Lanka", Code = "LK"},
                new Country {Name = "St. Barthélemy", Code = "BL"},
                new Country {Name = "St. Kitts and Nevis", Code = "KN"},
                new Country {Name = "St. Lucia", Code = "LC"},
                new Country {Name = "St. Martin", Code = "MF"},
                new Country {Name = "St. Pierre and Miquelon", Code = "PM"},
                new Country {Name = "St. Vincent and the Grenadines", Code = "VC"},
                new Country {Name = "Sudan", Code = "SD"},
                new Country {Name = "Suriname", Code = "SR"},
                new Country {Name = "Swaziland", Code = "SZ"},
                new Country {Name = "Sweden", Code = "SE"},
                new Country {Name = "Switzerland", Code = "CH"},
                new Country {Name = "Syria", Code = "SY"},
                new Country {Name = "Taiwan", Code = "TW"},
                new Country {Name = "Tajikistan", Code = "TJ"},
                new Country {Name = "Tanzania", Code = "TZ"},
                new Country {Name = "Thailand", Code = "TH"},
                new Country {Name = "Timor-Leste", Code = "TL"},
                new Country {Name = "Timor-Leste (East Timor)", Code = "TP"},
                new Country {Name = "Togo", Code = "TG"},
                new Country {Name = "Tokelau", Code = "TK"},
                new Country {Name = "Tonga", Code = "TO"},
                new Country {Name = "Trinidad and Tobago", Code = "TT"},
                new Country {Name = "Tristan da Cunha", Code = "TA"},
                new Country {Name = "Tunisia", Code = "TN"},
                new Country {Name = "Turkey", Code = "TR"},
                new Country {Name = "Turkmenistan", Code = "TM"},
                new Country {Name = "Turks and Caicos Islands", Code = "TC"},
                new Country {Name = "Tuvalu", Code = "TV"},
                new Country {Name = "Uganda", Code = "UG"},
                new Country {Name = "Ukraine", Code = "UA"},
                new Country {Name = "United Arab Emirates", Code = "AE"},
                new Country {Name = "United Kingdom", Code = "UK"},
                new Country {Name = "United States", Code = "US"},
                new Country {Name = "United States Minor Outlying Islands", Code = "UM"},
                new Country {Name = "Uruguay", Code = "UY"},
                new Country {Name = "Uzbekistan", Code = "UZ"},
                new Country {Name = "Vanuatu", Code = "VU"},
                new Country {Name = "Venezuela", Code = "VE"},
                new Country {Name = "Vietnam", Code = "VN"},
                new Country {Name = "Virgin Islands, British", Code = "VG"},
                new Country {Name = "Virgin Islands, U.S.", Code = "VI"},
                new Country {Name = "Wallis and Futuna", Code = "WF"},
                new Country {Name = "Yemen", Code = "YE"},
                new Country {Name = "Zambia", Code = "ZM"},
                new Country {Name = "Zimbabwe", Code = "ZW"}
            };

            context.Countries.AddOrUpdate(e => e.Id, countries);

            context.Users.AddOrUpdate(e => e.Id, new ApplicationUser
            {
                FirstName = "Gamunu",
                LastName = "Balagalla",
                Email = "gamunuud@gmail.com",
                PhoneNumberConfirmed = true,
                PhoneNumber = "94779226230",
                Country = "LK",
                EmailConfirmed = true,
                PasswordHash = new PasswordHasher().HashPassword("knight"),
                UserName = "Gamunu",
                BirthDate = DateTime.Now
            });

            var causes = new[]
            {
                new Cause {Name = "Neoplasms"},
                new Cause {Name = "Esophageal cancer"},
                new Cause {Name = "Stomach cancer"},
                new Cause {Name = "Liver cancer"},
                new Cause {Name = "Liver cancer secondary to hepatitis B"},
                new Cause {Name = "Liver cancer secondary to hepatitis C"},
                new Cause {Name = "Liver cancer secondary to alcohol use"},
                new Cause {Name = "Other liver cancer"},
                new Cause {Name = "Larynx cancer"},
                new Cause {Name = "Trachea, bronchus, and lung cancers"},
                new Cause {Name = "Breast cancer"},
                new Cause {Name = "Cervical cancer"},
                new Cause {Name = "Uterine cancer"},
                new Cause {Name = "Prostate cancer"}
            };

            context.Causes.AddOrUpdate(e => e.Id, causes);
        }
    }
}